### ISSUE TITLE
Addon does nothing

### ISSUE THREAD

**Issue by vasyugan** [queeup-archives/plugin.video.democracynow#1]
When launching the addon, all I get is an empty windows. I am running Kodi Jarvis on Libreelec, the Democracy Now! plugin is at version 2.0.4. 

This is what the log file says:

22:31:02 122.187752 T:1962893312   DEBUG: OnKey: return (0xf00d) pressed, action is Select
22:31:02 122.190285 T:1962893312   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.democracynow/)
22:31:02 122.190445 T:1962893312   DEBUG:   ParentPath = [addons://sources/video]
22:31:02 122.192711 T:1477428128   DEBUG: StartScript - calling plugin Democracy Now!('plugin://plugin.video.democracynow/','1','')
22:31:02 122.193214 T:1510982560   DEBUG: Thread LanguageInvoker start, auto delete: false
22:31:02 122.193382 T:1477428128   DEBUG: WaitOnScriptResult - waiting on the Democracy Now! (id=2) plugin...
22:31:02 122.193459 T:1510982560    INFO: initializing python engine.
22:31:02 122.193542 T:1510982560   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.democracynow/addon.py): start processing
22:31:02 122.252922 T:1510982560   DEBUG: -->Python Interpreter Initialized<--
22:31:02 122.253090 T:1510982560   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.democracynow/addon.py): the source file to load is "/storage/.kodi/addons/plugin.video.democracynow/addon.py"
22:31:02 122.253487 T:1510982560   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.democracynow/addon.py): setting the Python path to /storage/.kodi/addons/plugin.video.democracynow:/storage/.kodi/addons/script.module.beautifulsoup/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
22:31:02 122.253548 T:1510982560   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.democracynow/addon.py): entering source directory /storage/.kodi/addons/plugin.video.democracynow
22:31:02 122.253677 T:1510982560   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.democracynow/addon.py): instantiating addon using automatically obtained id of "plugin.video.democracynow" dependent on version 2.1.0 of the xbmc.python api
22:31:02 122.692215 T:1962893312   DEBUG: ------ Window Init (DialogBusy.xml) ------
22:31:04 124.261879 T:1477428128   DEBUG: WaitOnScriptResult- plugin returned successfully
22:31:04 124.262016 T:1510982560    INFO: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.democracynow/addon.py): script successfully run
22:31:04 124.269447 T:1552925600   DEBUG: Thread BackgroundLoader start, auto delete: false
22:31:04 124.284195 T:1552925600   DEBUG: Thread BackgroundLoader 1552925600 terminating
22:31:04 124.318153 T:1510982560    INFO: Python script stopped
22:31:04 124.318336 T:1510982560   DEBUG: Thread LanguageInvoker 1510982560 terminating
22:31:04 124.423233 T:1962893312   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
22:31:24 144.186783 T:1962893312   DEBUG: SECTION:UnloadDelayed(DLL: special://xbmcbin/system/ImageLib-arm.so

**Comment by queeup** [comment]
Thx for report. Until I fix it on the github you can fix it your self with changing this line:
https://github.com/queeup/plugin.video.democracynow/blob/gotham/addon.py#L58

```
if url.startswith('http://'):
```

to

```
if url.startswith('https://'):
```

I mean http to https

**Comment by queeup** [comment]
Fixed 2ecf3e2

**Comment by vasyugan** [comment]
Great, thanks! Just wondering, there is another addon called "Democracy Now Now" in the offical kodi repository and this immediately throws an error while loading. Is it also by you? If so, why don't you replace it with this one?

**Comment by queeup** [comment]
"Democracy Now Now" is not my add-on :(
