### ISSUE TITLE
Awesome addon!

### ISSUE THREAD

**Issue by leopheard** [queeup-archives/plugin.video.democracynow#6]
Thank you so much for this addon! I've been looking for this for ages!!

I don't suppose you could help me complete a podcast addon I've been trying to make? I'm having problems scraping titles, images and links from just a single site, but all the guides for python/beautifulsoup I've found are years old and Kodi has moved on since then. The forums are also pretty dead. I can see it all in the code, just have no idea how to pull them out and populate them into a page on the kodi addon.

My latest work is here: [](https://github.com/leopheard/thisiscriminal). I'd be quite happy to pay you for any help you can offer?

**Comment by queeup** [comment]
Thank you for your kind words. I hope I helped you a little.
