### ISSUE TITLE
Using github to host addon

### ISSUE THREAD

**Issue by leopheard** [queeup-archives/plugin.video.democracynow#7]
Sorry to totally hijack your page for a minute, but could you tell me how you are using Github to host your files? I've made a working podcast addon here: [https://github.com/leopheard/thisiscriminal](url), but neither that or [https://github.com/leopheard/thisiscriminal.git](url) seem to work when adding the source to install an addon .zip in the Kodi interface?

Also, how did you go about submitting it as an official addon? I've submitted an issue to their official Kodi repo page but I think a pull request would make more sense but have never done one before? Problem with Kodi is a lot of the guides etc. are from 2012-2013 etc

**Comment by queeup** [comment]
I didn't submit anything to official repo. Sorry, I can't help you with that.

I am hosting a addon repository on Github. You can check it [here](https://github.com/queeup/repository.queeup). I think It can help you to understand concept of repo and where to put your files. After that you can put that repo file to your Kodi. It allows you to download from your repo.

Or you can download zip file from your addons git page (https://github.com/leopheard/thisiscriminal/archive/master.zip) and tell kodi to install it.  The problem about this method is your directory name on the zip file must be same as your addon id (you can check it on the addon.xml)

## Example:
```console
$ unzip -l plugin.audio.thisiscriminal.zip 
Archive:  plugin.audio.thisiscriminal.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   113656  2009-12-09 14:37   plugin.audio.thisiscriminal/fanart.jpg
     2699  2019-05-13 16:32   plugin.audio.thisiscriminal/addon.xml
    19646  2009-12-10 02:33   plugin.audio.thisiscriminal/icon.png
     1024  2019-05-13 16:33   plugin.audio.thisiscriminal/changelog.txt
      482  2010-07-18 12:59   plugin.audio.thisiscriminal/LICENSE.txt
     3068  2019-05-13 16:10   plugin.audio.thisiscriminal/addon.py
---------                     -------
   140575                     6 files

```
